import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Inter, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { CircleCheckBig, CircleX } from "lucide-react";
import { Header, Footer } from "@/components/layout";
import { GoogleAnalytics } from "@next/third-parties/google";

const geist_mono = Geist_Mono({
  subsets: ["latin"]
});

const inter = Inter({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Samuel Oliveira | Portfolio",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      className={`${inter.className} ${geist_mono.className}`}
      suppressHydrationWarning
    >
      <body>
        <NextIntlClientProvider messages={messages}>
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                borderRadius: "8px",
                background: "#333",
                color: "#fff"
              },
              success: {
                style: {
                  background: "#508B26",
                  color: "#fff"
                },
                icon: <CircleCheckBig />
              },
              error: {
                style: {
                  background: "#ff4d4f", // vermelho
                  color: "#fff"
                },
                icon: <CircleX />
              },
              duration: 3000
            }}
          />
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div id="root" className="sr-only" />
            <Header />
            {children}
            <Footer />
            <GoogleAnalytics gaId={process.env.GA_ID!} />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
