import type { Metadata } from "next";
import "./globals.css";

import { Inter, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";

const geist_mono = Geist_Mono({
  subsets: ["latin"]
});

const inter = Inter({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Samuel Oliveira | Portfolio",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`${inter.className} ${geist_mono.className}`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
